
export enum UserRolesGuards {
    ROLE_REGISTERED = 'ROLE_REGISTERED',
    ROLE_UNREGISTERED = 'ROLE_UNREGISTERED',
    ROLE_ADMIN_CENTER = 'ROLE_ADMIN_CENTER',
    ROLE_ADMIN_SISTEM = 'ROLE_ADMIN_SISTEM',
    ROLE_MEDICAL_STUFF = 'ROLE_MEDICAL_STUFF'
  }
  